#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_balmung_hd2d = env_modules.Clone()
env_balmung_hd2d.add_source_files(env.modules_sources, "register_types.cpp")
env_balmung_hd2d.add_source_files(env.modules_sources, "balmung_hd2d_profile.cpp")
